#!/bin/bash

if ! [ $# -eq 3 ]; then
    echo "Usage: $0 <username> <cartridge> <source>"
    echo " source must be an absolute path to a source directory"
    exit 1
fi

platform/prepare.rb $1 $2-app cartridges/$2/manifest.yml $3
