#!/bin/bash

if ! [ $# -ge 3 ]; then
    echo "Usage: $0 <username> <app-name> <cartridge-name>"
    exit 1
fi

if ! [ -z "$4" ]; then
  platform/run.rb $1 $2 cartridges/$3/manifest.yml $4
else
  platform/run.rb $1 $2 cartridges/$3/manifest.yml
fi
